Add draft: Community Partner Highlight: African Institute of Biomedical Sciences and Technology (AiBST)
czi-catalystproject/czi-catalystproject.github.io pull request #98
Opened 2024-10-02 10:23 UTC by jnywong

Closes #91

2024-10-02 17:04 UTC, SLLDeC requested changes
Hi @jnywong I just left some minor changes.

2024-10-02 17:04 UTC, SLLDeC commented on catalystbook/blog/community-highlight-aibst-es.md
> +En esta publicación, Zedias Chikwambi comparte cómo la colaboración con el Proyecto Catalyst está impactando al Instituto Africano de Ciencias Biomédicas y Tecnología (AiBST, por African Institute of
When we mention the original name in English, it should be in italics.

```suggestion
En esta publicación, Zedias Chikwambi comparte cómo la colaboración con el Proyecto Catalyst está impactando al Instituto Africano de Ciencias Biomédicas y Tecnología (AiBST, por _African Institute of Biomedical Sciences and Technology_) en Zimbabue.
```

2024-10-02 17:04 UTC, SLLDeC commented on catalystbook/blog/community-highlight-aibst-es.md
> +Soy Zedias Chikwambi del Instituto Africano de Ciencias Biomédicas y Tecnología (AiBST) en Zimbabue. Nuestra misión es descubrir y utilizar biomarcadores para guiar tratamientos personalizados. Aprov
```suggestion
Soy Zedias Chikwambi del Instituto Africano de Ciencias Biomédicas y Tecnología (AiBST) en Zimbabue. Nuestra misión es descubrir y utilizar biomarcadores para guiar tratamientos personalizados. Aprovechamos una amplia gama de herramientas genómicas, incluidas bases de datos de secuenciación de nueva generación (NGS, por _Next Generation Sequencing_) , datos clínicos y plataformas computacionales avanzadas como los recursos en la nube del Proyecto Catalyst, para identificar y refinar biomarcadores. Estos biomarcadores se aplican en el desarrollo de herramientas de diagnóstico y detección de última generación. Los recursos computacionales a los que tenemos acceso han sido fundamentales para realizar análisis bioinformáticos exhaustivos en conjuntos de datos genómicos. Actualmente, nuestra comunidad de AiBST cuenta con cinco participantes activos, y estamos comprometidos en aumentar este número a través de iniciativas de formación locales y regionales.
```

2024-10-02 17:04 UTC, SLLDeC commented on catalystbook/blog/community-highlight-aibst-es.md
> +A través del Proyecto Catalyst podemos llevar la interpretación de la información genómica a la cabecera del paciente.
```suggestion
"A través del Proyecto Catalyst podemos llevar la interpretación de la información genómica a la cabecera del paciente."
```

2024-10-02 17:04 UTC, SLLDeC commented on catalystbook/blog/community-highlight-aibst-es.md
> +Esta iniciativa está liderada por la Unidad de Genómica de AiBST, donde aprovechamos y celebramos la diversidad de variaciones genómicas entre individuos para entender mejor las respuestas a medicame
```suggestion
Esta iniciativa está liderada por la Unidad de Genómica de AiBST, donde aprovechamos y celebramos la diversidad de variaciones genómicas entre individuos para entender mejor las respuestas a medicamentos e informar sobre terapias personalizadas. Nuestro trabajo incluye la generación y utilización de conjuntos de datos genómicos y clínicos, como datos transcriptómicos (tanto a nivel de célula única como a nivel de núcleos/células en conjunto), secuenciación completa del exoma (WES, por _Whole Exome Sequencing_), secuenciación completa del genoma (WGS, por _Whole Genome Sequencing_) y datos de genotipos obtenidos mediante plataformas de open array para polimorfismos de un solo nucleótido (SNPs, por _Single Nucleotide Polymorphisms_) y variaciones en el número de copias (CNVs, por _Copy Number Variations_). Utilizamos herramientas avanzadas como pipelines de identificación de variantes, R, Python y plataformas de visualización de datos para analizar e interpretar estos datos.
```

2024-10-14 14:57 UTC, jnywong commented on catalystbook/blog/community-highlight-aibst-en.md
> +Through the Catalyst Project we are able to bring genomic information interpretation to patient bedsides."
```suggestion
"Through the Catalyst Project we are able to bring genomic information interpretation to patient bedsides."
```

2024-10-14 14:59 UTC, merged