Community Partner Highlight - Malawi University of Science and Technology (MUST)
czi-catalystproject/czi-catalystproject.github.io pull request #99
Opened 2024-10-02 11:02 UTC by jnywong

Closes #92

2024-10-02 17:08 UTC, SLLDeC requested changes

2024-10-02 17:08 UTC, SLLDeC commented on catalystbook/blog/community-highlight-must-es.md
> +author: Katie Pratt (CSCCE), Sabrina López (MetaDocencia)
```suggestion
author: Katie Pratt (CSCCE), Kevin Cabana, (MetaDocencia), Sabrina López (MetaDocencia)
```

2024-10-02 17:08 UTC, SLLDeC commented on catalystbook/blog/community-highlight-must-es.md
> +El Proyecto Catalyst en la Universidad de Ciencia y Tecnología de Malawi ha llegado en el momento justo, cuando muchos profesores y estudiantes necesitaban una plataforma robusta y de fácil acceso de
```suggestion
"El Proyecto Catalyst en la Universidad de Ciencia y Tecnología de Malawi ha llegado en el momento justo, cuando muchos profesores y estudiantes necesitaban una plataforma robusta y de fácil acceso desde la cual pudieran ejecutar eficientemente sus modelos de aprendizaje automático y realizar análisis avanzados para su investigación en ciencia de datos, sin necesidad de estar físicamente en el campus".
```

2024-10-02 17:08 UTC, SLLDeC commented on catalystbook/blog/community-highlight-must-es.md
> +En esta publicación, Bennett Kankuzi comparte cómo la colaboración con el Proyecto Catalyst está impactando a la Universidad de Ciencia y Tecnología de Malawi  (MUST, por Malawi University of Science
```suggestion
En esta publicación, Bennett Kankuzi comparte cómo la colaboración con el Proyecto Catalyst está impactando a la Universidad de Ciencia y Tecnología de Malawi  (MUST, por _Malawi University of Science and Technology_).
```

2024-10-14 14:58 UTC, jnywong commented on catalystbook/blog/community-highlight-must-en.md
> +The Catalyst Project at Malawi University of Science and Technology has come at the right time when many staff and students needed a robust and easily accessible platform from which they could effici
```suggestion
"The Catalyst Project at Malawi University of Science and Technology has come at the right time when many staff and students needed a robust and easily accessible platform from which they could efficiently run their machine learning models and do advanced data analysis for their data science research without even being physically available on campus."
```

2024-10-14 14:59 UTC, merged